### ISSUE TITLE
Entity beans implement interface

### ISSUE THREAD

**Issue by ykrasik** [ebean-orm/avaje-ebeanorm-agent#15]
Hi,

I'm trying to get Ebean to enhance my entity beans which implement an interface, but it fails on ArrayIndexOutOfBoundsException.

Right now the interface is just a marker interface without any functionality, but the reasoning is that some of the tables in the DB represent Enum values (which are not under my control, I need to be able to translate an Enum out of a table row), so each of these table that represents an Enum would implement the EnumTable interface that has a getCode() method (or something) that would make translating Enums out of rows a generic, reusable piece of code.

Full example:
```
@Entity
@Table(name = "ab_test_types")
public class AbTestTypes implements EnumTable {
    private static final long serialVersionUID = 1L;

    @Id
    @Basic(optional = false)
    @Column(name = "ab_test_type_id")
    private Short id;

    @Basic(optional = false)
    @Column(name = "ab_test_type_code")
    private String code;

    public AbTestTypes() {
    }

    public AbTestTypes(Short id) {
        this.id = id;
    }

    public Short getId() {
        return id;
    }

    public void setId(Short id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }
}
```

```
public interface EnumTable {
}
```

```
java.lang.ArrayIndexOutOfBoundsException: 165
	at com.avaje.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:174)
	at com.avaje.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:153)
	at com.avaje.ebean.enhance.agent.ClassMetaReader.readFromResource(ClassMetaReader.java:64)
	at com.avaje.ebean.enhance.agent.ClassMetaReader.getWithCache(ClassMetaReader.java:36)
	at com.avaje.ebean.enhance.agent.ClassMetaReader.get(ClassMetaReader.java:27)
	at com.avaje.ebean.enhance.agent.EnhanceContext.getInterfaceMeta(EnhanceContext.java:146)
	at com.avaje.ebean.enhance.agent.ClassAdapterDetectEnhancement.visit(ClassAdapterDetectEnhancement.java:137)
	at com.avaje.ebean.enhance.asm.ClassReader.accept(ClassReader.java:553)
	at com.avaje.ebean.enhance.asm.ClassReader.accept(ClassReader.java:420)
	at com.avaje.ebean.enhance.agent.Transformer.detect(Transformer.java:252)
	at com.avaje.ebean.enhance.agent.Transformer.transform(Transformer.java:106)
	at com.avaje.ebean.enhance.agent.InputStreamTransform.transform(InputStreamTransform.java:55)
	at com.avaje.ebean.enhance.agent.InputStreamTransform.transform(InputStreamTransform.java:39)
```

It seems like it doesn't matter whether the bean extends an abstract class or implements an interface, it results in the same exception.

Ebean version: 4.5.5
Ebean agent version: 4.5.2

**Comment by rbygrave** [comment]
So this didn't reproduce with the test added with commit 4c8df78

**Comment by rbygrave** [comment]
So ClassReader is a copy (repackaging) of org.objectweb.asm.ClassReader. Line 174 ... in theory it didn't parse the constant pool.  

I wonder what version of java is being used here?

**Comment by rbygrave** [comment]
Not able to reproduce by extending an abstract class either.

**Comment by rbygrave** [comment]
Ebean's ClassReader is from ASM 5.0.3 tag:  So Rev 1748: (root)/tags/ASM_5_0_3/src/org/objectweb/asm/ClassReader.java - Rev 1748

... and there are changes to ClassReader in trunk:
(root)/trunk/asm/src/org/objectweb/asm/ClassReader.java - Rev 1773

Diff from 1773 to 1748:
http://websvn.ow2.org/log.php?repname=asm&path=%2Ftrunk%2Fasm%2Fsrc%2Forg%2Fobjectweb%2Fasm%2FClassReader.java&sr=1773&er=1748&max=40&search=

**Comment by ykrasik** [comment]
Hi,

Sorry I didn't mention the Java version, it's j8u40.

**Comment by rbygrave** [comment]
Ok, working with  1.8.0_25-b17.

**Comment by rbygrave** [comment]
Hmmm. Tests still all passing with:
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

Are you able to try agent 4.5.3?  It should not make any difference in theory but worth checking if possible.

Alternatively, are you able to git clone the avaje-ebeanorm-agent project and run all the tests via:  mvn clean test?

Cheers, Rob.

**Comment by ykrasik** [comment]
Will do and let you know, also trying with j8u25.

**Comment by ykrasik** [comment]
Slightly different exception with j8u25 - 
```
java.lang.IllegalArgumentException
	at com.avaje.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:170)
	at com.avaje.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:153)
	at com.avaje.ebean.enhance.agent.ClassMetaReader.readFromResource(ClassMetaReader.java:65)
	at com.avaje.ebean.enhance.agent.ClassMetaReader.getWithCache(ClassMetaReader.java:35)
	at com.avaje.ebean.enhance.agent.ClassMetaReader.get(ClassMetaReader.java:27)
	at com.avaje.ebean.enhance.agent.EnhanceContext.getInterfaceMeta(EnhanceContext.java:138)
	at com.avaje.ebean.enhance.agent.ClassAdapterDetectEnhancement.visit(ClassAdapterDetectEnhancement.java:108)
	at com.avaje.ebean.enhance.asm.ClassReader.accept(ClassReader.java:622)
	at com.avaje.ebean.enhance.asm.ClassReader.accept(ClassReader.java:506)
	at com.avaje.ebean.enhance.agent.Transformer.detect(Transformer.java:254)
	at com.avaje.ebean.enhance.agent.Transformer.transform(Transformer.java:108)
	at com.avaje.ebean.enhance.agent.InputStreamTransform.transform(InputStreamTransform.java:55)
	at com.avaje.ebean.enhance.agent.InputStreamTransform.transform(InputStreamTransform.java:39)
```

This happens when trying to read the entity implemented Interface's bytes, the value returned at ClassReader:169 is 25888.

However, this is for a large project that also has other libraries that depend on asm's ClassReader, so maybe this is interfering somehow.
I will try cloning & running the tests tomorrow, will let you know.

**Comment by ykrasik** [comment]
OK, so... I was doing all this through IntelliJ's Ebean plugin (https://github.com/ykrasik/idea-ebean-enhancer), which I hadn't updated in a while.

It's using a custom ClassBytesReader, which is the link between IDEA and the enhancer. Long story short, the problem was here - the implementation was passing the .java class's bytes, instead of the compiled .class bytes.

I created a much more robust handling mechanism for providing .class bytes in the ClassBytesReader which fixes this.
I'll upload the plugin soon to the IntelliJ plugins repo.

Thanks for your help!

**Comment by rbygrave** [comment]
Ok great.
