### ISSUE TITLE
_ebean_intercept field missing when @MappedSuperclass with no persistent fields but has hashCode() and equals()

### ISSUE THREAD

**Issue by dastultz** [ebean-orm/avaje-ebeanorm-agent#28]
I am trying to update my enhancer agent from 4.1.4 to 4.9.1. Everything after 4.1.4 is failing me (even 4.1.5). I have a `PersistentEntity` class that is the `@MappedSuperclass` of all my entities. `PersistentEntity` does not have any fields to be persisted nor does it define `@Id`. When I have a direct subclass, there is no `_ebean_intercept` field defined. When I do have an intermediate class, say `AbstractRole` that sits between `PersistentEntity` and `Role` and `AbstractRole` defines `@Id`, I do get `_ebean_intercept` defined (in `AbstractRole`) .

With 4.1.4 of the agent, `PersistentEntity` gets `_ebean_intercept` (and others) defined.

**Comment by rbygrave** [comment]
You need to create a test case.

Create a small maven project that uses the maven enhancer or uses the
javaagent and reproduce the problem?

**Comment by rbygrave** [comment]
Thought, is PersistentEntity not abstract?  Show me the entity code in question and the stack trace if you can.

**Comment by rbygrave** [comment]
Notes:
https://github.com/ebean-orm/avaje-ebeanorm/tree/master/src/test/java/com/avaje/tests/model/mappedsuper
https://github.com/ebean-orm/avaje-ebeanorm/blob/master/src/test/java/com/avaje/ebeaninternal/server/deploy/TestNotEnhancedMappedSuper.java

**Comment by dastultz** [comment]
Attached is an Eclipse project that reproduces the problem. I'd be jazzed if there were a Maven project I could clone and use as a template for such things. I just don't know enough about Maven to put it together.

The file database.sql creates and populates a PostgreSQL database. Main.java contains a very simple query and Ebean fails trying to create the EbeanServer. `PersistentEntity` is abstract, yes.

I used the runtime agent. 4.1.4 works, 4.1.10 fails.

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at Main.main(Main.java:6)
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldError: _ebean_intercept
	at com.avaje.ebean.Ebean$ServerManager.<init>(Ebean.java:173)
	at com.avaje.ebean.Ebean$ServerManager.<init>(Ebean.java:133)
	at com.avaje.ebean.Ebean.<clinit>(Ebean.java:127)
	... 1 more
Caused by: java.lang.NoSuchFieldError: _ebean_intercept
	at Role._ebean_set_defaultTimeDebit(Role.java:1)
	at Role.<init>(Role.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at java.lang.Class.newInstance0(Class.java:357)
	at java.lang.Class.newInstance(Class.java:310)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptor.createPrototypeEntityBean(BeanDescriptor.java:513)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptor.<init>(BeanDescriptor.java:369)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:648)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:305)
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:130)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:122)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:75)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:42)
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:55)
	at com.avaje.ebean.Ebean$ServerManager.getWithCreate(Ebean.java:210)
	at com.avaje.ebean.Ebean$ServerManager.<init>(Ebean.java:168)
```

[ebean-bug.zip](https://github.com/ebean-orm/avaje-ebeanorm-agent/files/163400/ebean-bug.zip)

**Comment by rbygrave** [comment]
I have run the test case and reproduced.

This error specifically is triggered by the existence of the hashCode() and equals() methods in the mapped superclass PersistentEntity

```java

	@Override
	public int hashCode() { return getId().hashCode(); }

	@Override
	public boolean equals(Object object) { return getId().equals(((PersistentEntity)this).getId()); }

```

**Comment by rbygrave** [comment]
Interesting enough is that the hashCode() / equals() used here effectively does the same as the implementation that Ebean enhancement would give you (but the implementation above always assumes there is an non-null Id value.

**Comment by rbygrave** [comment]
Where I think this bug has arisen from is that ... a while back the enhancement treatment of MappedSuperclass changed such that they did not need to be enhanced IF they didn't have any persistent properties.  This one does not have persistent properties but does override hashCode()/equals() so I think the bug is that ... the existence of hashCode/equals should trigger the enhancement of this mapped superclass and is not doing so.

**Comment by rbygrave** [comment]
Refined to be:

```java
    Agenda a = new Agenda();
    a.setName("foo");
    System.out.println(a.getName());
```

Producing:

Exception in thread "main" java.lang.NoSuchFieldError: _ebean_intercept
	at some.Agenda._ebean_set_name(Agenda.java:1)
	at some.Agenda.setName(Agenda.java:22)
	at some.Main.main(Main.java:11)

**Comment by rbygrave** [comment]
Enhancement logging:

ebean-enhance> cls: test/model/AMappedSuperWithEquals  msg: performing detection
ebean-enhance> cls: test/model/AMappedSuperWithEquals  msg: interfaces:  entityInterface[false] transactional[false]
ebean-enhance> cls: test/model/AMappedSuperWithEquals  msg: visitAnnotation Ljavax/persistence/MappedSuperclass;
ebean-enhance> cls: test/model/AMappedSuperWithEquals  msg: found entity annotation Ljavax/persistence/MappedSuperclass;
ebean-enhance> cls: test/model/AMappedSuperWithEquals  msg: visitMethod <init> ()V
ebean-enhance> cls: test/model/AMappedSuperWithEquals  msg: visitMethod hashCode ()I
ebean-enhance> cls: test/model/AMappedSuperWithEquals  msg: visitMethod equals (Ljava/lang/Object;)Z
ebean-enhance> cls: test/model/AMappedSuperWithEquals  msg: performing entity transform
ebean-enhance> cls: test/model/AMappedSuperWithEquals  msg: ... add EntityBean interface
ebean-enhance> cls: test/model/AMappedSuperWithEquals  msg: mappedSuperClass with equals/hashCode or persistentFields: false
ebean-enhance> cls: test/model/AMappedSuperWithEquals  msg: skipping... no enhancement required

... but AMappedSuperWithEquals does have equals/hashCode so there is the bug in that detection.

**Comment by dastultz** [comment]
I have verified in my real project that my super class is properly enhanced now. Oddly the test case I sent still fails but not for the same reason. The test case uses the runtime agent and produces "Bean class Role is not enhanced?".

**Comment by allnash** [comment]
There  seems to be a regression of this bug, ugh!

**Comment by rbygrave** [comment]
Create a failing test for us @allnash  ... TestNotEnhancedMappedSuper test is still passing etc so no evidence of a regression.
